name: ApexSandboxCTV-tvOS
options:
  minimumXcodeGenVersion: 2.41.0
  deploymentTarget:
    tvOS: "16.0"
packages:
  RivalApexMediationSDK:
    path: ../../../sdk/core/ios
targets:
  ApexSandboxCTV-tvOS:
    type: application
    platform: tvOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
        includes:
          - "**/*.swift"
    resources:
      - path: Sources
        includes:
          - "**/*.json"
          - "**/*.plist"
    dependencies:
      - package: RivalApexMediationSDK
        product: RivalApexMediationSDK
    settings:
      INFOPLIST_FILE: Sources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.apex.sandbox.tvos
      SWIFT_VERSION: 5.0
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_STYLE: Manual
      DEVELOPMENT_TEAM: ""
    scheme:
      testTargets: []
